"""boem_bsee — US Gulf of Mexico boreholes (BOEM data center) + field-lease
discovery proxy (spec §5, §18.3 "the messy one").

Inputs (registry-verified 2026-07-18; both regenerated by BOEM, anonymous GET):

- ``https://www.data.boem.gov/Well/Files/BoreholeRawData.zip`` — one member,
  ``BoreholeRawData/mv_boreholes_all.txt``: 57,446 boreholes, 26 columns,
  header row, quoted fields that keep leading spaces *inside* the quotes
  (``"  162"``, ``" 00023"``), unquoted M/D/YYYY dates, embedded commas in
  quoted company names. Filtered to ``REGION_CODE == 'G'`` (Gulf of Mexico;
  55,513 rows on 2026-07-18 — P/A/Y regions are out of scope for this source).
- ``https://www.data.boem.gov/FieldReserves/Files/mastdatadelimit.zip`` — one
  member ``mastdatadelimit.txt``: the Field Names Master List (field→lease),
  NO header row, 10 quoted comma-delimited columns. Column meaning verified
  against the ALLFIELDLEASES1 record layout
  (https://www.data.boem.gov/Main/HtmlPage.aspx?page=fieldNames1) and
  cross-checked against Appendix A (area/block→field/lease index): col 0 =
  FIELD_NAME_CODE, col 1 = LEASE_NUMBER, then area, block, EIA field code,
  operator, FLD_LSE_EFF_DATE, FLD_LSE_EXPIR_DT, LEASE_STATUS_CD, FLD_LSE_DESC.
  Old (pre-OCS-numbering) leases carry a leading space (``" 00023"``) — both
  sides of the join are stripped.

OUTCOME IS A LEASE-LEVEL DISCOVERY PROXY — NOT A PER-WELL RESULT
----------------------------------------------------------------
BOEM's borehole file has no per-well content/outcome field. ``content_raw`` is
synthesized from the lease→field join:

- ``FIELD_LEASE_MATCH`` — the borehole's BOTM_LEASE_NUMBER appears in the
  Field Names Master List, i.e. BOEM assigned that lease to a discovered field.
- ``NO_FIELD_LEASE``  — it does not (includes the literal lease values
  ``NOLEASE`` and ``DPST`` — deep stratigraphic tests — which by construction
  never match).

Known, card-carried biases of the proxy: every well on a matched lease
inherits the match, so appraisal/development wells on a discovered lease are
"successes" regardless of their own result, and a dry wildcat drilled on a
lease that LATER proved productive is a false positive; conversely a genuine
single-well discovery whose lease was never formally assigned to a field is a
false negative. Directionally it is informative (E-wells match 74.1% vs
D-wells 98.9% on 2026-07-18), but per-well truth it is not. The dataset card
must carry this caveat wherever boem_bsee labels appear.

Purpose mapping (WELL_TYPE_CODE → purpose)
------------------------------------------
Legend live-verified 2026-07-18 from the Borehole query page dropdown
(https://www.data.boem.gov/Well/Borehole/Default.aspx): C=Core Test,
D=Development, E=Exploratory, N=Non-Operation, O=Other, R=Relief, S=Strat Test.

- ``E`` → ``wildcat``. BOEM has NO wildcat/appraisal distinction — "E" is any
  exploratory borehole, conflating true wildcats with appraisal/delineation
  wells. Documented limitation for the card; the with/without-appraisal
  sensitivity run cannot separate them for this source.
- ``D`` → ``other`` (development), and ``C``/``N``/``O``/``R``/``S`` →
  ``other`` (core test / non-operation / other / relief / strat test — none is
  an exploration decision). Observed in region G on 2026-07-18: D=35,575,
  E=19,782, C=117, R=38, O=1 (N and S exist in the legend and in other
  regions — e.g. the Atlantic COST wells are ``S`` — but not in G that day).
  A code outside the legend RAISES; it is never bucketed silently.

Units, datum, and other cleaning decisions (§18.3: every choice documented)
---------------------------------------------------------------------------
- ``BH_TOTAL_MD`` is in FEET: the fixed-width record layout
  (https://www.data.boem.gov/Main/HtmlPage.aspx?page=borehole) states feet
  explicitly for the sibling depth fields (RKB Elevation, True Vertical
  Depth) measured from the same kelly bushing, and the observed maximum
  (37,743) is only physical as feet (~11.5 km; as metres it would be a 37 km
  hole). Converted with ``FT_TO_M`` = 0.3048 → ``td_m``. Blank stays missing;
  the two literal ``0`` values in the live file are kept as 0.0 — verbatim
  data, not imputed away.
- ``*****`` in BH_TOTAL_MD (414 rows on 2026-07-18, every one a 2023–24 spud,
  always masking TVD/TD_SS too) is BOEM's proprietary-period withholding of
  recent well depths — an explicit "value withheld" sentinel
  (``DEPTH_WITHHELD``), not a number and not an accident. td_m stays missing,
  the row stays. Surface coordinates are never masked. Any OTHER non-numeric
  depth value still raises — new sentinels must be reviewed, never coerced.
- Coordinates: SURF_LATITUDE/SURF_LONGITUDE, 100% populated in region G. The
  ASCII layout does not declare a datum (BOEM GIS products for the GoM are
  NAD27); the NAD27↔WGS84 shift in the Gulf is tens of metres — far below the
  0.05° modeling grid — so coordinates are passed through untransformed and
  the schema pins Gulf bounds (lat 23–32, lon −98…−80) to catch sign/axis/
  datum catastrophes loudly.
- ``WELL_SPUD_DATE`` is M/D/YYYY, unquoted; 1,021 blanks in region G stay
  missing (Int64 NA) — harmonize drops and counts them downstream, we do not.
  A non-blank date that fails M/D/YYYY parsing raises (format drift).
- ``well_id`` = ``"boem:" + API_WELL_NUMBER`` (12-digit API, unique across
  the live file). Only full-row hard duplicates are dropped; conflicting rows
  sharing a PK survive to fail the schema's uniqueness check loudly.
- ``discovery_id`` = the matched FIELD_NAME_CODE(s). 315 leases map to more
  than one field (a lease can straddle fields); the codes are joined sorted
  with ``+`` (e.g. ``WD027+WD030``) — deterministic, no arbitrary winner.
- An empty field-lease master, zero Gulf rows, or missing columns raise —
  an empty-but-fresh label table is §0's worst outcome.
"""

from __future__ import annotations

import io
import zipfile

import pandas as pd
import pandera.pandas as pa

from erda_contracts.errors import ContractViolation, SourceUnavailable
from erda_ingestion.base import FetchResult, http_get

SOURCE_ID = "boem_bsee"
TRANSFORM_VERSION = "boem_bsee:1.0.0"
TABLE = "boem_bsee_wells"

BOREHOLE_ZIP_URL = "https://www.data.boem.gov/Well/Files/BoreholeRawData.zip"
MASTDATA_ZIP_URL = "https://www.data.boem.gov/FieldReserves/Files/mastdatadelimit.zip"

#: International foot; BH_TOTAL_MD is feet per the BOEM record layout (see
#: module docstring — RKB/TVD siblings are documented "in feet").
FT_TO_M = 0.3048

#: WELL_TYPE_CODE → purpose. Complete over the live-verified legend on the
#: BOEM Borehole query page (2026-07-18). BOEM's "E" conflates wildcat and
#: appraisal — documented limitation. An unlisted code raises, never defaults.
PURPOSE_MAP = {
    "E": "wildcat",  # Exploratory (wildcat + appraisal, indistinguishable)
    "D": "other",  # Development
    "C": "other",  # Core Test
    "N": "other",  # Non-Operation
    "O": "other",  # Other
    "R": "other",  # Relief
    "S": "other",  # Strat Test
}

#: The synthesized lease-level proxy codes (see module docstring).
CONTENT_MATCH = "FIELD_LEASE_MATCH"
CONTENT_NO_MATCH = "NO_FIELD_LEASE"

#: BOEM masks depth fields of recent (proprietary-period) wells with '*****'
#: — an explicit "value withheld" sentinel, mapped to missing (docstring).
DEPTH_WITHHELD = "*****"

#: Borehole columns normalize() actually consumes; absence = schema drift.
REQUIRED_BOREHOLE_COLUMNS = [
    "API_WELL_NUMBER",
    "WELL_SPUD_DATE",
    "BH_TOTAL_MD",
    "WELL_TYPE_CODE",
    "SURF_LATITUDE",
    "SURF_LONGITUDE",
    "BOTM_LEASE_NUMBER",
    "REGION_CODE",
]

#: ALLFIELDLEASES1 record layout (headerless delimited file) — verified against
#: https://www.data.boem.gov/Main/HtmlPage.aspx?page=fieldNames1 and Appendix A.
MASTDATA_COLUMNS = [
    "field_name_code",
    "lease_number",
    "area_code",
    "block_number",
    "eia_field_code",
    "sort_name",
    "fld_lse_eff_date",
    "fld_lse_expir_dt",
    "lease_status_cd",
    "fld_lse_desc",
]

COLUMNS = [
    "well_id",
    "lat",
    "lon",
    "spud_year",
    "purpose_raw",
    "purpose",
    "content_raw",
    "td_m",
    "discovery_id",
]

SCHEMA = pa.DataFrameSchema(
    {
        "well_id": pa.Column(str, pa.Check.str_startswith("boem:"), nullable=False),
        # Gulf of Mexico bounds with margin (observed 25.9–30.2 / −97.2…−83.4).
        # Untransformed source datum (see docstring); a swapped axis, positive
        # longitude, or datum catastrophe fails here instead of poisoning labels.
        "lat": pa.Column(float, pa.Check.in_range(23.0, 32.0), nullable=True),
        "lon": pa.Column(float, pa.Check.in_range(-98.0, -80.0), nullable=True),
        # Observed 1947–2026; blanks stay NA (harmonize drops-and-counts later).
        "spud_year": pa.Column("Int64", pa.Check.in_range(1900, 2100), nullable=True),
        "purpose_raw": pa.Column(str, pa.Check.isin(list(PURPOSE_MAP)), nullable=False),
        "purpose": pa.Column(str, pa.Check.isin(["wildcat", "appraisal", "other"]), nullable=False),
        "content_raw": pa.Column(
            str, pa.Check.isin([CONTENT_MATCH, CONTENT_NO_MATCH]), nullable=False
        ),
        "td_m": pa.Column(float, pa.Check.ge(0), nullable=True),
        "discovery_id": pa.Column(str, nullable=True),
    },
    unique=["well_id"],
)


def extract_member(zip_bytes: bytes, what: str) -> io.BytesIO:
    """Return the single ``.txt`` member of a BOEM zip; anything else is drift."""
    try:
        archive = zipfile.ZipFile(io.BytesIO(zip_bytes))
    except zipfile.BadZipFile as exc:
        raise SourceUnavailable(SOURCE_ID, f"{what} is not a zip: {exc}") from exc
    members = [n for n in archive.namelist() if n.lower().endswith(".txt")]
    if len(members) != 1:
        raise SourceUnavailable(SOURCE_ID, f"expected exactly one .txt in {what}, found {members}")
    return io.BytesIO(archive.read(members[0]))


def read_boreholes(handle) -> pd.DataFrame:
    """Borehole CSV → all-string frame. ``keep_default_na=False`` is load-bearing:
    blank spud dates / depths must arrive as '' (explicit absence), never NaN."""
    df = pd.read_csv(handle, dtype=str, keep_default_na=False)
    missing = [c for c in REQUIRED_BOREHOLE_COLUMNS if c not in df.columns]
    if missing:
        raise ContractViolation(SOURCE_ID, f"borehole file missing columns: {missing}")
    return df


def read_field_leases(handle) -> pd.DataFrame:
    """Headerless field→lease master → named all-string frame (10 columns exactly)."""
    try:
        df = pd.read_csv(handle, header=None, dtype=str, keep_default_na=False)
    except pd.errors.ParserError as exc:
        raise ContractViolation(SOURCE_ID, f"field-lease master unparseable: {exc}") from exc
    if df.shape[1] != len(MASTDATA_COLUMNS):
        raise ContractViolation(
            SOURCE_ID,
            f"field-lease master has {df.shape[1]} columns, expected "
            f"{len(MASTDATA_COLUMNS)} (ALLFIELDLEASES1 layout drifted?)",
        )
    df.columns = MASTDATA_COLUMNS
    return df


def _numeric(
    series: pd.Series, name: str, missing: frozenset[str] = frozenset({""})
) -> pd.Series:
    """Strict str→float: values in ``missing`` → NA, anything else non-numeric raises."""
    stripped = series.str.strip()
    values = pd.to_numeric(stripped.where(~stripped.isin(missing)), errors="coerce")
    bad = sorted(set(stripped[values.isna() & ~stripped.isin(missing)]))
    if bad:
        raise ContractViolation(SOURCE_ID, f"non-numeric {name} values: {bad[:10]}")
    return values


def normalize(boreholes: pd.DataFrame, field_leases: pd.DataFrame) -> pd.DataFrame:
    """Raw borehole + field-lease frames → pre-harmonize well rows.

    Pure; raises instead of guessing. Scope filter: REGION_CODE == 'G' only
    (the source is defined as the Gulf of Mexico). Within scope no row is
    dropped except full-row hard duplicates by PK.
    """
    missing = [c for c in REQUIRED_BOREHOLE_COLUMNS if c not in boreholes.columns]
    if missing:
        raise ContractViolation(SOURCE_ID, f"borehole frame missing columns: {missing}")
    if list(field_leases.columns) != MASTDATA_COLUMNS:
        raise ContractViolation(SOURCE_ID, "field-lease frame does not follow ALLFIELDLEASES1")
    if field_leases.empty:
        # An empty master would silently label every well NO_FIELD_LEASE.
        raise ContractViolation(SOURCE_ID, "field-lease master is empty — refusing proxy join")

    df = boreholes[boreholes["REGION_CODE"].str.strip() == "G"].copy()
    if df.empty:
        raise ContractViolation(
            SOURCE_ID, "zero REGION_CODE=='G' rows — refusing an empty-but-fresh table"
        )

    api = df["API_WELL_NUMBER"].str.strip()
    if (api == "").any():
        raise ContractViolation(SOURCE_ID, f"{(api == '').sum()} rows missing API_WELL_NUMBER (PK)")

    spud = df["WELL_SPUD_DATE"].str.strip()
    parsed = pd.to_datetime(spud.where(spud != ""), format="%m/%d/%Y", errors="coerce")
    bad_dates = sorted(set(spud[parsed.isna() & (spud != "")]))
    if bad_dates:
        raise ContractViolation(
            SOURCE_ID, f"WELL_SPUD_DATE not M/D/YYYY: {bad_dates[:10]} — format drifted"
        )

    type_code = df["WELL_TYPE_CODE"].str.strip()
    unknown = sorted(set(type_code) - set(PURPOSE_MAP))
    if unknown:
        raise ContractViolation(
            SOURCE_ID,
            f"WELL_TYPE_CODE {unknown} outside the verified legend — "
            "classify explicitly in PURPOSE_MAP; silent 'other' could hide exploration wells",
        )

    # Lease-level discovery proxy (see module docstring): strip both sides —
    # old leases are ' 00023' in the master and sometimes in the borehole file.
    lease = df["BOTM_LEASE_NUMBER"].str.strip()
    master_lease = field_leases["lease_number"].str.strip()
    master_field = field_leases["field_name_code"].str.strip()
    lease_to_fields = master_field.groupby(master_lease).apply(
        lambda fields: "+".join(sorted(set(fields)))
    )
    discovery_id = lease.map(lease_to_fields)

    out = pd.DataFrame(
        {
            "well_id": "boem:" + api,
            "lat": _numeric(df["SURF_LATITUDE"], "SURF_LATITUDE"),
            "lon": _numeric(df["SURF_LONGITUDE"], "SURF_LONGITUDE"),
            "spud_year": parsed.dt.year.astype("Int64"),
            "purpose_raw": type_code,
            "purpose": type_code.map(PURPOSE_MAP),
            "content_raw": discovery_id.notna().map({True: CONTENT_MATCH, False: CONTENT_NO_MATCH}),
            "td_m": _numeric(df["BH_TOTAL_MD"], "BH_TOTAL_MD", frozenset({"", DEPTH_WITHHELD}))
            * FT_TO_M,
            "discovery_id": discovery_id.astype(object).where(discovery_id.notna(), None),
        },
        columns=COLUMNS,
    )
    # Hard duplicates only: identical rows collapse; conflicting rows sharing a
    # PK survive to fail the schema's uniqueness check loudly.
    return out.drop_duplicates().reset_index(drop=True)


def fetch() -> FetchResult:
    """Download both zips (~3.5 MB + ~0.1 MB), extract, normalize.

    Provenance carries the borehole zip URL; the field-lease master URL that
    the content_raw proxy derives from is cited in
    data/curated/outcome_map.d/boem_bsee.csv and in the module docstring.
    """
    bore_resp = http_get(BOREHOLE_ZIP_URL, SOURCE_ID, timeout=300.0)
    mast_resp = http_get(MASTDATA_ZIP_URL, SOURCE_ID, timeout=120.0)
    boreholes = read_boreholes(extract_member(bore_resp.content, "borehole zip"))
    field_leases = read_field_leases(extract_member(mast_resp.content, "field-lease master zip"))
    return FetchResult(frame=normalize(boreholes, field_leases), source_url=BOREHOLE_ZIP_URL)
